openapi: 3.0.0
info:
  title: Module Data API
  version: 1.0.0
  description: API for fetching specific module data for a given symbol.
paths:
  /api/finance/module:
    get:
      summary: Get module data for a symbol
      parameters:
        - in: query
          name: symbol
          schema:
            type: string
          required: true
          description: Stock symbol
        - in: query
          name: module
          schema:
            type: string
          required: true
          description: Module type
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Server Error
